name: Deploy to production

on:
  push:
    branches:
      - "prod"

jobs:
  IntegrationTest:
    runs-on: ubuntu-latest

    name: IntegrationTest

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('./package.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'

        run: |
          yarn install

      - name: Build
        run: |
          cp src/config.example.js src/config.js
          yarn run format
          yarn run build

  deploy:
    name: deploy
    needs: [IntegrationTest]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 20.232.127.81
          port: 22
          username: indresh
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ./SIH/hyper-office-client
            git checkout .
            git fetch origin prod
            git reset --hard origin/prod
            yarn install
            yarn run build
            cd build
            mkdir .well-known
            cd .well-known
            cat ${{ secrets.ASSETLINKS_KEY }} > assetlinks.json
